### ISSUE TITLE
Name request is not defined

### ISSUE THREAD

**Issue by KobaKhit** [simonv3/quickbooks-python#10]
I may be doing something wrong. Basically, I am following the directions in the readme file and when I get to the `request.GET['oauth_token']` I get an error `NameError: name 'request' is not defined`. I was looking for the request function and could not figure where it is or how it is supposed to be defined. Thanks for any help.

**Comment by simonv3** [comment]
Hey KobaKhit, the request is however you're handling your requests to a server. In the case of the readme, it's Django's [`request`](https://docs.djangoproject.com/en/dev/ref/request-response/) object. 

I know nothing about your code or infrastructure, so I would suggest looking at however you get access to HTTP request parameters, which is where the oauth_token will appear. 

I'll specify that in the readme.

**Comment by KobaKhit** [comment]
I got past this problem. Thanks.
